### ISSUE TITLE
Web scraping for RJPS

### ISSUE THREAD

**Issue by littlepea** [littlepea/safeway-data#13]
This [source](https://rjps.mpips.gov.pl/RJPS/WJ/start.do?stronaListy=1&liczbaPozycjiLista=20&wersja=1&widocznyPanel=mapa) has 3000+ verified helping points across Poland, this could greatly boost our database and have more resources for refugees using the app in Poland.

When we scrape we need to make sure that we map their categories to [our categories](https://github.com/littlepea/safeway-data/blob/master/config/constants.py#L3).

The best way to scrape it is to actually consume the API powering the map rather than trying to scrape web pages.

For example, our first list of URLs to scrape would be a query for each category, for example, for `Seniors` we would select all the subcategories:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/575716/169758161-cac78473-4c9e-4559-a4e6-746a215135b9.png">

That leans that we'd need to POST to https://rjps.mpips.gov.pl/RJPS/WJ/wyszukiwanie/zaladujDane.do API the following payload:

```json
{"filtry":{"miejscowosc":"","wojewodztwo":"","powiat":"","gmina":"","odleglosc":0,"lokalizacja":"","szukanaFraza":"","podkategorie":"21,22,23,24,20,19","stronaListy":1,"liczbaPozycjiLista":"20","wersja":"1","widocznyPanel":"mapa","wejscieKarta":"","idJednostki":""},"stronaListy":1}
```

Where `21,22,23,24,20,19` are the IDs of the subcategories, so we know that any results coming out of this request will belong to the category `Seniors`.

That will return a list of point IDs with coordinates like so:

```json
[{"id":2321,"x":18.59832,"y":52.55788},{"id":2354,"x":18.49855,"y":52.998119},...]
```

Then, we can use each ID to make a detail GET request to https://rjps.mpips.gov.pl/RJPS/WJ/wyszukiwanie/pobierzDaneJednostki.do?jednostkiIds=3499 which gives us HTML for point description which we can parse accordingly.

**Comment by idisblueflash** [comment]
Could you provide some background of scraping?
For example, why we need such data, what will we use them later?

Looks like we can scraping from [a list of center](https://rjps.mpips.gov.pl/RJPS/WJ/start.do?stronaListy=1&liczbaPozycjiLista=20&wersja=1&widocznyPanel=lista)
![Screenshot 2022-05-23 at 8 21 26 AM](https://user-images.githubusercontent.com/14199/169722797-4d268799-57a4-4a3e-b1eb-fc5257dc81e7.png)

**Comment by littlepea** [comment]
@idisblueflash I've updated the description

**Comment by littlepea** [comment]
See [Creating new spiders](https://github.com/littlepea/safeway-data#creating-new-spiders).

**Comment by idisblueflash** [comment]
thanks!
And could I take this Issue as my next contribution?

**Comment by littlepea** [comment]
@idisblueflash Yes, sure, thanks! 🙏

**Comment by idisblueflash** [comment]
> When we scrape we need to make sure that we map their categories to [our categories](https://github.com/littlepea/safeway-data/blob/master/config/constants.py#L3).

How could we make a good match? Looks like it's hard to match well.
<img width="1107" alt="Screenshot 2022-05-26 at 6 50 20 PM" src="https://user-images.githubusercontent.com/14199/170474166-3fa36dfb-96f7-44db-8869-2457a2dfdc51.png">

**Comment by littlepea** [comment]
* Seniors -> Medical
* Family -> Children
* People with disabilities -> Disability support
* Children and youth -> Children
* Addiction -> Mental help
* Health -> Medical
* Violence -> Social help
* Difficult financial situation -> Finance

**Comment by idisblueflash** [comment]
iIs that ok to parse like below?
<img width="1036" alt="Screenshot 2022-05-26 at 8 37 02 PM" src="https://user-images.githubusercontent.com/14199/170489598-feef1124-cb46-45f3-b0c2-f173561fd396.png">
https://rjps.mpips.gov.pl/RJPS/WJ/wyszukiwanie/pobierzDaneJednostki.do?jednostkiIds=3500

**Comment by littlepea** [comment]
> iIs that ok to parse like below?

Yes, but I wouldn't put `organizations` there, just leave it empty.
And description could be:

```
Social welfare Center

email. gops@gminazawady.pl
tel. 7140116

updated: 2018-01-25
```

> and for city, I still don't have a good way to parse them out from the address,
> or maybe we can fetch out with the geocoding.py service, but I guess it should be another User Story.

Yes, that could be solved later with reverse geocoding once we implement #10

**Comment by littlepea** [comment]
@idisblueflash I've ran the scraper but the resulting CSV has no coordinates... How is it possible if we've scraped from a map?

**Comment by littlepea** [comment]
And when I try to enrich it with `poetry run python main.py --input-file data/poland_rjps.csv` I get zero results that pass the validation (even after geocoding).

**Comment by idisblueflash** [comment]
looks like https://github.com/littlepea/safeway-data/pull/33/files#r895169853 can resolve this issue
then we can get output data with `city` was filled in.

> How is it possible if we've scraped from a map?

I'm not sure. But in geo response, we can extract the city name.
![Screenshot 2022-06-12 at 19 42 54](https://user-images.githubusercontent.com/14199/173234610-09ca943b-37db-4c6e-b50a-6cb0b5d09b9d.png)

**Comment by littlepea** [comment]
> I'm not sure. But in geo response, we can extract the city name.

Can we do it, please?

And, also, make sure we scrape `lat/lng` too (right now, they are empty)

**Comment by idisblueflash** [comment]
> Can we do it, please?

Yes we can
But I think after the Reverse geocoding finished https://github.com/littlepea/safeway-data/pull/33
we can have it automatically.
Then there's no need to do it here.

> we scrape lat/lng too (right now, they are empty)

We can't scrape this info, since there's no such data on the page.
But as I investigated, we can get them during the `self.geocoder.enhance` step,
thus we'll have lat/lng automatically as well.

**Comment by littlepea** [comment]
> But I think after the Reverse geocoding finished https://github.com/littlepea/safeway-data/pull/33
> we can have it automatically.
> Then there's no need to do it here.

We should get as much as possible from scraping so that we minimize the number of geocoding requests

> We can't scrape this info, since there's no such data on the page.

It was in the JSON from the beginning for each point with `id/lat/lng`

**Comment by idisblueflash** [comment]
> It was in the JSON from the beginning for each point with id/lat/lng

Yes, you're right.
I thought it was the location on picture, so I ignored.

> We should get as much as possible from scraping so that we minimize the number of geocoding requests

Sure
But for the city, we didn't know which word it's a city name, which it not from the address.
How could we extract it then? It's a tricky one.

**Comment by littlepea** [comment]
Ok, let's just get the coordinates and reverse-geocode the city

**Comment by littlepea** [comment]
@idisblueflash just curious, why `organizations` value is always `Poland RJPS`?

**Comment by idisblueflash** [comment]
Good question!

I didn't understand the organisation before, thus leaving it empty.
And @moorchegue helped with a hardcoded `Plan RJPS`.

As a second look, I think we can use a `type` field here.
For example, we can extract these:
- Social welfare Center
- Municipal family support center
- Poviat family support center
It looks like an organisation name.

**Comment by littlepea** [comment]
@idisblueflash no, no, if there's no obvious `organizations` we should just leave it empty, let's not come up with data, only use if it's there

**Comment by idisblueflash** [comment]
make sense

Let me make a quick fix then.
