### ISSUE TITLE
Web scraping for French Red Cross

### ISSUE THREAD

**Issue by littlepea** [littlepea/safeway-data#15]
This [source](https://www.croix-rouge.fr/Annuaire?structure_type%5B%5D=1&structure_type%5B%5D=2&structure_type%5B%5D=3&structure_type%5B%5D=4&field=-1&sector=-1&department=-1&address=&searchBtn=Rechercher) has 1500+ verified helping points across France, this could greatly boost our database and have more resources for refugees using the app in France.

When we scrape we need to make sure that we map their categories to [our categories](https://github.com/littlepea/safeway-data/blob/master/config/constants.py#L3).

**Comment by littlepea** [comment]
See [Creating new spiders](https://github.com/littlepea/safeway-data#creating-new-spiders).

**Comment by moorchegue** [comment]
I'll take this, please!

**Comment by littlepea** [comment]
@moorchegue Thank you! 🙏
