### ISSUE TITLE
Translate city names to English

### ISSUE THREAD

**Issue by littlepea** [littlepea/safeway-data#6]
Sometimes a [PointOfInterest](https://github.com/littlepea/safeway-data/blob/master/models/point_of_interest.py) can [have a city name in a local language](https://github.com/littlepea/safeway-data/blob/master/tests/test_geocoding.py), in which case we could translate it automatically in English by using a translation API like:

* https://cloud.google.com/translate/docs/reference/rest/
* https://docs.microsoft.com/en-us/rest/api/cognitiveservices/translator/translator/translate
* https://docs.aws.amazon.com/translate/latest/dg/examples-python.html
* etc...

The task is to implement the [CityTranslator](https://github.com/littlepea/safeway-data/blob/master/services/translation.py) to find translations for all cities from points and fill them back onto those points.

We already have a [failing test](https://github.com/littlepea/safeway-data/blob/master/tests/test_translation.py) and you need to make it pass ✌ 

P.S. Let @littlepea know if you need help obtaining API keys

**Comment by idisblueflash** [comment]
please assign this for me

**Comment by idisblueflash** [comment]
Do you think we should handle this new case?
city: Wien/Vienna 
looks like Wien is the one we need to translate,
then Vienna is English.

I'm not sure we have a lot of such cases, `Other Language City/English City`


how about making `Wien/Vienna` to `Vienna` as a solution?

**Comment by littlepea** [comment]
Yeah, we could handle those as a special case, so if `/` in city name we would use `city.split["/"][-1]` as translation

**Comment by idisblueflash** [comment]
@littlepea please review #14
